# Generated by Django 4.1.2 on 2022-11-02 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('idtype', models.CharField(max_length=50)),
                ('idnumber', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=50)),
                ('room_size', models.CharField(max_length=50)),
                ('room_type', models.CharField(max_length=50)),
                ('room_price', models.CharField(max_length=50)),
                ('reserved_room', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('idtype', models.CharField(max_length=50)),
                ('idnumber', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inDateTime', models.DateTimeField(auto_now_add=True)),
                ('outDateTime', models.DateTimeField(null=True)),
                ('Visitor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='HotelApp.visitor')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='HotelApp.rooms')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('idtype', models.CharField(max_length=50)),
                ('idnumber', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('salary', models.CharField(max_length=10)),
                ('account_number', models.CharField(max_length=20)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='HotelApp.department')),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_people', models.CharField(max_length=10)),
                ('checkin_datetime', models.DateTimeField(auto_now_add=True)),
                ('checkout_datetime', models.DateTimeField(null=True)),
                ('amount', models.CharField(max_length=20)),
                ('Guest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='HotelApp.guest')),
                ('Room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='HotelApp.rooms')),
            ],
            options={
                'verbose_name_plural': 'Bookings',
            },
        ),
    ]
